# Generated by Django 4.2.27 on 2025-12-05 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('individual', 'Individual'), ('alumni', 'Alumni'), ('corporate', 'Corporate'), ('school', 'School')], default='individual', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('kra_pin', models.CharField(blank=True, max_length=50)),
                ('alumni_school', models.CharField(blank=True, max_length=200)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_registration', models.CharField(blank=True, max_length=100)),
                ('company_address', models.TextField(blank=True)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('school_name', models.CharField(blank=True, max_length=200)),
                ('school_type', models.CharField(blank=True, max_length=50)),
                ('school_registration', models.CharField(blank=True, max_length=100)),
                ('school_address', models.TextField(blank=True)),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('staff_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
