# Generated by Django 6.0 on 2025-12-17 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0006_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='store.employer'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_salaried_employee',
            field=models.BooleanField(default=False),
        ),
    ]
