# Generated by Django 4.2.27 on 2025-12-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_brand_cart_classroompackage_donationamount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="First line of heading (e.g., 'Your Gateway to')", max_length=100)),
                ('highlight', models.CharField(help_text="Highlighted text (e.g., 'Smart Technology')", max_length=100)),
                ('badge_text', models.CharField(help_text='Badge text above title', max_length=100)),
                ('description', models.TextField(help_text='Description paragraph')),
                ('primary_button_text', models.CharField(max_length=50)),
                ('primary_button_link', models.CharField(max_length=200)),
                ('secondary_button_text', models.CharField(max_length=50)),
                ('secondary_button_link', models.CharField(max_length=200)),
                ('image', models.ImageField(help_text='Hero image (recommended: 800x600px)', upload_to='hero_slides/')),
                ('card_icon', models.CharField(choices=[('phone', 'Phone/Mobile'), ('building', 'Building/Enterprise'), ('computer', 'Computer/Education'), ('shopping', 'Shopping Bag')], default='phone', max_length=20)),
                ('card_label', models.CharField(help_text="e.g., 'Starting from'", max_length=50)),
                ('card_price', models.CharField(help_text="e.g., 'KES 2,999'", max_length=50)),
                ('card_subtext', models.CharField(help_text="e.g., '/month with financing'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
