# Generated by Django 4.2.26 on 2025-12-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_heroslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='card_price',
            field=models.CharField(help_text="e.g., 'Ksh 2,999'", max_length=50),
        ),
        migrations.CreateModel(
            name='TradeInRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('current_device', models.CharField(max_length=200)),
                ('device_condition', models.CharField(choices=[('excellent', 'Excellent - Like New'), ('good', 'Good - Minor Scratches'), ('fair', 'Fair - Visible Wear'), ('poor', 'Poor - Functional but Damaged')], default='good', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('variant_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_in_requests', to='store.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productvariant')),
            ],
            options={
                'verbose_name': 'Trade-In Request',
                'verbose_name_plural': 'Trade-In Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
