# Generated by Django 6.0 on 2025-12-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationboard',
            name='specifications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='educationtablet',
            name='specifications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, default=''),
        ),
    ]
