# Generated by Django 6.0 on 2025-12-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_school_fundraiser_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='background_color',
            field=models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('teal', 'Teal'), ('red', 'Red'), ('indigo', 'Indigo'), ('amber', 'Amber'), ('cyan', 'Cyan')], default='green', help_text='Background color theme for this slide', max_length=20),
        ),
    ]
