# Generated by Django 6.0 on 2025-12-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_heroslide_background_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms of Service'), ('cookies', 'Cookie Policy'), ('returns', 'Return Policy'), ('shipping', 'Shipping Policy'), ('refund', 'Refund Policy'), ('warranty', 'Warranty Policy')], help_text='Type of policy - each type can only have one entry', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Page title', max_length=200)),
                ('content', models.TextField(help_text='Policy content (supports HTML)')),
                ('last_updated', models.DateField(help_text='Date the policy was last updated')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'ordering': ['policy_type'],
            },
        ),
    ]
