# Generated by Django 6.0 on 2026-01-07 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_orderitem_education_tablet_alter_orderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, help_text='Bank code (e.g., KCB, EQUITY)', max_length=50, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='banks/')),
                ('branch', models.CharField(blank=True, help_text='Main branch', max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('api_endpoint', models.URLField(blank=True, help_text='Bank API endpoint for credit checks')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner Bank',
                'verbose_name_plural': 'Partner Banks',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='financingapplication',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='financing_certificates/'),
        ),
        migrations.AddField(
            model_name='financingapplication',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_applications', to='store.employer'),
        ),
        migrations.AddField(
            model_name='financingapplication',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='financingapplication',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='financingapplication',
            name='application_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('chama', 'Chama/Group'), ('corporate', 'Corporate'), ('salaried', 'Salaried Worker')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financingapplication',
            name='employer_name',
            field=models.CharField(blank=True, help_text='Used if employer not in list', max_length=200),
        ),
        migrations.AlterField(
            model_name='financingapplication',
            name='preferred_bank',
            field=models.CharField(blank=True, help_text='Legacy field', max_length=100),
        ),
        migrations.AlterField(
            model_name='financingapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('bank_review', 'Bank Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='financingapplication',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_applications', to='store.bank'),
        ),
    ]
